---
version: '3'
services:
  freqtrade:
    container_name: ft-$CONFIG
    env_file: $ENV_FILE
    # image: freqtradeorg/freqtrade:stable
    image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # Make sure to uncomment the whole deploy section
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    volumes:
      - ./user_data:/freqtrade/user_data # create user_data from tempate first
      - ../_data/kraken:/freqtrade/user_data/data/kraken
    # https://www.freqtrade.io/en/stable/rest-api/
    ports:
      - 8080:8080
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy ichiV1_Marius
